# Generated by Django 4.2.16 on 2026-04-05 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'Étudiant(e)'), ('professeur', 'Professeur'), ('pat', 'Personnel administratif et technique'), ('responsable', 'Responsable des communications'), ('admin', 'Administrateur'), ('superuser', 'Super administrateur')], default='eleve', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create_user', 'Création de membre'), ('update_user', 'Modification de membre'), ('delete_user', 'Suppression de membre'), ('toggle_active', 'Activation/Désactivation'), ('import_users', 'Import de membres'), ('idea_status', "Changement de statut d'idée"), ('idea_create', "Soumission d'idée"), ('idea_pin', "Épinglage d'idée"), ('comment_moderate', 'Modération de commentaire')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
