# Generated by Django 4.2.16 on 2026-04-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'Étudiant(e)'), ('professeur', 'Professeur'), ('pat', 'Personnel administratif et technique'), ('directeur', 'Directeur'), ('responsable', 'Responsable des communications'), ('admin', 'Administrateur'), ('superuser', 'Super administrateur')], default='eleve', max_length=20),
        ),
    ]
