# Generated by Django 4.2.16 on 2026-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('hors_perimetre', 'Hors périmètre'), ('budget', 'Budget insuffisant'), ('deja_en_cours', 'Déjà en cours'), ('doublon', "Doublon d'une idée existante"), ('non_realisable', 'Non réalisable techniquement'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('en_etude', 'En étude'), ('acceptee', 'Acceptée'), ('mise_en_oeuvre', 'En cours de mise en œuvre'), ('realisee', 'Réalisée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20),
        ),
    ]
