# Generated by Django 4.2.16 on 2026-04-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_rejection_category_alter_idea_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['status'], name='idea_status_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['created_at'], name='idea_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['is_pinned', 'created_at'], name='idea_pinned_created_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['author', 'status'], name='idea_author_status_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['category', 'status'], name='idea_category_status_idx'),
        ),
    ]
